# Climate-watch notebook 
datascience case

1. Create database 
2. Creat jupyter notebook
3. Clean database
4. Assignements
5. Power BI

In [2]:
import pandas as pd
import matplotlib as plt
import geopandas as gpd
import sqlalchemy as SA

In [3]:
# connect to database
engine = SA.create_engine("mysql+pymysql://root:TrinaDePipa@localhost/climate_watch?charset=utf8mb4")

In [4]:
sql = "SELECT * FROM globaltemperatures"
df = pd.read_sql(sql, engine)
df.head()

,id,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1,1750-01-01,3.034,3.574,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1750-02-01,3.083,3.702,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1750-03-01,5.626,3.076,0.0,0.0,0.0,0.0,0.0,0.0
3,4,1750-04-01,8.490,2.451,0.0,0.0,0.0,0.0,0.0,0.0
4,5,1750-05-01,11.573,2.072,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
sql = " SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
df = pd.read_sql(sql, engine)
df.head(8)

            TABLE_NAME
0                 city
1              country
2       globaltempcity
3    globaltempcountry
4   globaltemperatures
5  globaltempmajorcity
6      globaltempstate
7                state

### Clean code
tables:
- globaltemperatures
- globaltempcity
- globaltempcountry
- globaltempstate
- globaltempmajorcity
- city
- state
- country

In [ ]:
inspector = SA.inspect(engine)
table_names = inspector.get_table_names()
table_names

for table in table_names:
    columns = inspector.get_columns(table)      
    for col in columns:
        if col['type'].__class__.__name__ in ('INTEGER', 'FLOAT', 'DECIMAL', 'NUMERIC'):
            with engine.begin() as conn:
                sql = SA.text(f"UPDATE {table} SET {col} = null WHERE {col} = 0")
                result = conn.execute(sql)
                print(f"{table} - {col} : {result.rowcount} rows are updated")
        else: 
            print(f"{table} - {col} : 0 rows are updated")

city - id : 0 rows are updated
city - name : 0 rows are updated
city - country_id : 0 rows are updated
country - id : 0 rows are updated
country - name : 0 rows are updated
globaltempcity - id : 0 rows are updated
globaltempcity - dt : 0 rows are updated
globaltempcity - averagetemperature : 364205 rows are updated
globaltempcity - averagetemperatureuncertainty : 364130 rows are updated
globaltempcity - city_id : 0 rows are updated
globaltempcity - latitude : 0 rows are updated
globaltempcity - longitude : 83557 rows are updated
globaltempcountry - id : 0 rows are updated
globaltempcountry - dt : 0 rows are updated
globaltempcountry - AverageTemperature : 32658 rows are updated
globaltempcountry - AverageTemperatureUncertainty : 31912 rows are updated
globaltempcountry - country_id : 0 rows are updated
globaltemperatures - id : 0 rows are updated
globaltemperatures - dt : 0 rows are updated
globaltemperatures - LandAverageTemperature : 12 rows are updated
globaltemperatures - LandAverageTemperatureUncertainty : 12 rows are updated
globaltemperatures - LandMaxTemperature : 1200 rows are updated
globaltemperatures - LandMaxTemperatureUncertainty : 1200 rows are updated
globaltemperatures - LandMinTemperature : 1200 rows are updated
globaltemperatures - LandMinTemperatureUncertainty : 1200 rows are updated
globaltemperatures - LandAndOceanAverageTemperature : 1200 rows are updated
globaltemperatures - LandAndOceanAverageTemperatureUncertainty : 1200 rows are updated
globaltempmajorcity - id : 0 rows are updated
globaltempmajorcity - dt : 0 rows are updated
globaltempmajorcity - averagetemperature : 11334 rows are updated
globaltempmajorcity - averagetemperatureuncertainty : 11328 rows are updated
globaltempmajorcity - city_id : 0 rows are updated
globaltempmajorcity - latitude : 0 rows are updated
globaltempmajorcity - longitude : 6478 rows are updated
globaltempstate - id : 0 rows are updated
globaltempstate - dt : 0 rows are updated
globaltempstate - averagetemperature : 25663 rows are updated
globaltempstate - averagetemperatureuncertainty : 25648 rows are updated
globaltempstate - state_id : 0 rows are updated
state - id : 0 rows are updated
state - name : 241 rows are updated
state - country_id : 0 rows are updated

In [ ]:
sql = "select * from country"
df = pd.read_sql(sql, engine)
df.head()

TypeError: string indices must be integers, not 'str'