# Climate-watch notebook 
datascience case

1. Create database 
2. Creat jupyter notebook
3. Clean database
4. Assignements
5. Power BI

In [33]:
import pandas as pd
import matplotlib as plt
import geopandas as gpd
import sqlalchemy as SA
import numpy as np

In [2]:
# connect to database
engine = SA.create_engine("mysql+pymysql://root:TrinaDePipa@localhost/climate_watch?charset=utf8mb4")

In [3]:
sql = "SELECT * FROM globaltemperatures"
df = pd.read_sql(sql, engine)
df.head()

,id,dt,LandAverageTemperature,LandAverageTemperatureUncertainty,LandMaxTemperature,LandMaxTemperatureUncertainty,LandMinTemperature,LandMinTemperatureUncertainty,LandAndOceanAverageTemperature,LandAndOceanAverageTemperatureUncertainty
0,1,1750-01-01,3.034,3.574,0.0,0.0,0.0,0.0,0.0,0.0
1,2,1750-02-01,3.083,3.702,0.0,0.0,0.0,0.0,0.0,0.0
2,3,1750-03-01,5.626,3.076,0.0,0.0,0.0,0.0,0.0,0.0
3,4,1750-04-01,8.490,2.451,0.0,0.0,0.0,0.0,0.0,0.0
4,5,1750-05-01,11.573,2.072,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
sql = " SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE'"
df = pd.read_sql(sql, engine)
df.head(8)

            TABLE_NAME
0                 city
1              country
2       globaltempcity
3    globaltempcountry
4   globaltemperatures
5  globaltempmajorcity
6      globaltempstate
7                state

### Clean code
tables:
- globaltemperatures
- globaltempcity
- globaltempcountry
- globaltempstate
- globaltempmajorcity
- city
- state
- country

All zero-values are set to NaN. These values can easily be replaced by mean value when necessary.

In [ ]:
inspector = SA.inspect(engine)
table_names = inspector.get_table_names()

for table in table_names:
    columns = inspector.get_columns(table)
    for col in columns:
        if col['type'].__class__.__name__ in ('INTEGER', 'FLOAT', 'DECIMAL', 'NUMERIC'):
            with engine.begin() as conn:
                sql = SA.text(f"UPDATE {table} SET {col['name']} = null WHERE {col['name']} = 0")
                result = conn.execute(sql)
                print(f"{table} - {col['name']} : {result.rowcount} rows are updated")
        else: 
            print(f"{table} - {col['name']} : 0 rows are updated")

city - id : 0 rows are updated
city - name : 0 rows are updated
city - country_id : 0 rows are updated
country - id : 0 rows are updated
country - name : 0 rows are updated
globaltempcity - id : 0 rows are updated
globaltempcity - dt : 0 rows are updated
globaltempcity - averagetemperature : 0 rows are updated
globaltempcity - averagetemperatureuncertainty : 0 rows are updated
globaltempcity - city_id : 0 rows are updated
globaltempcity - latitude : 0 rows are updated
globaltempcity - longitude : 0 rows are updated
globaltempcountry - id : 0 rows are updated
globaltempcountry - dt : 0 rows are updated
globaltempcountry - AverageTemperature : 0 rows are updated
globaltempcountry - AverageTemperatureUncertainty : 0 rows are updated
globaltempcountry - country_id : 0 rows are updated
globaltemperatures - id : 0 rows are updated
globaltemperatures - dt : 0 rows are updated
globaltemperatures - LandAverageTemperature : 0 rows are updated
globaltemperatures - LandAverageTemperatureUncertainty : 0 rows are updated
globaltemperatures - LandMaxTemperature : 0 rows are updated
globaltemperatures - LandMaxTemperatureUncertainty : 0 rows are updated
globaltemperatures - LandMinTemperature : 0 rows are updated
globaltemperatures - LandMinTemperatureUncertainty : 0 rows are updated
globaltemperatures - LandAndOceanAverageTemperature : 0 rows are updated
globaltemperatures - LandAndOceanAverageTemperatureUncertainty : 0 rows are updated
globaltempmajorcity - id : 0 rows are updated
globaltempmajorcity - dt : 0 rows are updated
globaltempmajorcity - averagetemperature : 0 rows are updated
globaltempmajorcity - averagetemperatureuncertainty : 0 rows are updated
globaltempmajorcity - city_id : 0 rows are updated
globaltempmajorcity - latitude : 0 rows are updated
globaltempmajorcity - longitude : 0 rows are updated
globaltempstate - id : 0 rows are updated
globaltempstate - dt : 0 rows are updated
globaltempstate - averagetemperature : 0 rows are updated
globaltempstate - averagetemperatureuncertainty : 0 rows are updated
globaltempstate - state_id : 0 rows are updated
state - id : 0 rows are updated
state - name : 0 rows are updated
state - country_id : 0 rows are updated

## Opdrachten

### 1. Exploration
- Verken de algemene statistieken van de data (mean, median, standard deviation, etc.) dmv df.describe() of andere functies
- Verken de distributie van de temperatuurwaarden over de jaren. Door bijvoorbeeld waarden te groeperen in jaren of eeuwen.
- Visualiseer de trend in de global average land temperatures over de tijd

In [53]:
temperature_tables = table_names[2:7]

for table in temperature_tables:
    sql = f'SELECT * FROM {table}'
    df = pd.read_sql(SA.text(sql), engine)
    df_temp= df.filter(regex = r'(Temp|temp)', axis = 1)
    print(table)
    print(df_temp.describe())

globaltempcity
       averagetemperature  averagetemperatureuncertainty
count        8.235007e+06                   8.235082e+06
mean         1.672758e+01                   1.028575e+00
std          1.035337e+01                   1.129733e+00
min         -4.270400e+01                   3.400000e-02
25%          1.029900e+01                   3.370000e-01
50%          1.883100e+01                   5.910000e-01
75%          2.521000e+01                   1.349000e+00
max          3.965100e+01                   1.539600e+01
globaltempcountry
       AverageTemperature  AverageTemperatureUncertainty
count       544804.000000                  545550.000000
mean            17.193575                       1.019057
std             10.953863                       1.201930
min            -37.658000                       0.052000
25%             10.026000                       0.323000
50%             20.901000                       0.571000
75%             25.814000                       1.206000
max             38.842000                      15.003000
globaltemperatures
       LandAverageTemperature  LandAverageTemperatureUncertainty  \
count             3180.000000                        3180.000000
mean                 8.374731                           0.938468
std                  4.381310                           1.096440
min                 -2.080000                           0.034000
25%                  4.312000                           0.186750
50%                  8.610500                           0.392000
75%                 12.548250                           1.419250
max                 19.021000                           7.880000

       LandMaxTemperature  LandMaxTemperatureUncertainty  LandMinTemperature  \
count         1992.000000                    1992.000000         1992.000000
mean            14.350601                       0.479782            2.743595
std              4.309579                       0.583203            4.155835
min              5.900000                       0.044000           -5.407000
25%             10.212000                       0.142000           -1.334500
50%             14.760000                       0.252000            2.949500
75%             18.451500                       0.539000            6.778750
max             21.320000                       4.373000            9.715000

       LandMinTemperatureUncertainty  LandAndOceanAverageTemperature  \
count                    1992.000000                     1992.000000
mean                        0.431849                       15.212566
std                         0.445838                        1.274093
min                         0.045000                       12.475000
25%                         0.155000                       14.047000
50%                         0.279000                       15.251000
75%                         0.458250                       16.396250
max                         3.498000                       17.611000

       LandAndOceanAverageTemperatureUncertainty
count                                1992.000000
mean                                    0.128532
std                                     0.073587
min                                     0.042000
25%                                     0.063000
50%                                     0.122000
75%                                     0.151000
max                                     0.457000
globaltempmajorcity
       averagetemperature  averagetemperatureuncertainty
count       247659.000000                  247665.000000
mean            17.807303                       0.977437
std             10.104316                       1.005463
min            -26.772000                       0.040000
25%             11.963000                       0.340000
50%             20.099000                       0.590000
75%             25.801000                       1.322000
max             38.283000                      14.037000
globaltempstate
       averagetemperature  averagetemperatureuncertainty
count       620012.000000                  620027.000000
mean             8.993328                       1.287647
std             13.772246                       1.360392
min            -45.389000                       0.036000
25%             -0.693000                       0.316000
50%             11.199000                       0.656000
75%             19.899000                       1.850000
max             36.339000                      12.646000

In [55]:
sql = "select * from globaltempstate where averagetemperature is NULL and averagetemperatureuncertainty is not null"
df = pd.read_sql(sql, engine)
df.head()

,id,dt,averagetemperature,averagetemperatureuncertainty,state_id
0,77484,1952-12-01,None,0.465,32
1,105527,1841-12-01,None,2.386,43
2,111127,1820-12-01,None,1.860,45
3,171354,1833-02-01,None,2.140,69
4,177173,1814-03-01,None,2.766,70